### ISSUE TITLE
Migrate to textx-tools and a question about this repo

### ISSUE THREAD

**Issue by simkimsia** [igordejanovic/textx-gen-er-flask#1]
Hi @igordejanovic 

2 questions:

1. can you move this to textx-tools?
2. so this code will take in a ER model and convert it to SQLalchemy code yes? So can I model this for say Django models?

**Comment by igordejanovic** [comment]
1. Sure. This will be moved to textX organization together with the rest of the stuff.
2. Exactly. That was the idea. I don't remember how complete this code is but generally should be a good starting point for writing generator for Django.

**Comment by simkimsia** [comment]
>Exactly. That was the idea. 

You have no idea how happy I am to hear this :)
